### api cliente get
GET http://localhost:8080/api/v1/users

### api cliente post
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
    "name": "julia",
    "email": "fer@hgd.com.br",
    "age": "21",
    "password": "feck54@",
    "title": "Harry Potter",
    "author": "J.K. Rowling",
    "category": "Fantasy",
    "isFree": true,
    "year": 2000,
    "status": "READ",
    "rating": 5,
    "comment": "",
    "type": ""
}

### api cliente put
PUT http://localhost:8080/api/v1/users/1
Content-Type: application/json

{
    "name": "julia engeler",
    "email": "fer@hgd.com.br",
    "age": "21",
    "password": "feck54@",
    "title": "Harry Potter",
    "author": "J.K. Rowling",
    "category": "Fantasy",
    "isFree": false,
    "year": 2000,
    "status": "READ",
    "rating": 5,
    "comment": "",
    "type": "Paypal"
}

### api cliente delete
DELETE http://localhost:8080/api/v1/users/1